; Example dialplan snippet updated to use DID lookup API.
[did-lookup]
exten => _361X.,1,AGI(agi://127.0.0.1:4577/call_log)
 same => n,Set(API_Response=${CURL(http://138.201.138.161:8080/did_lookup.php?dialed_number=${EXTEN:3})})
 same => n,GotoIf($["${API_Response}"="0"]?hangup)
 same => n,Set(CALLERID(num)=1${API_Response})
 same => n,Dial(SIP/DG/99999#${EXTEN:3},,T)
 same => n,Hangup()

exten => hangup,1,Hangup()
